---
title: "Outline of eDiscovery paper"
author: "Richard Careaga"
date: "February 8, 2019"

output: 
    html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
suppressPackageStartupMessages(library(latentnet))
suppressPackageStartupMessages(library(network))
#suppressPackageStartupMessages(library(rebus))
suppressPackageStartupMessages(library(statnet))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(tm))
#suppressPackageStartupMessages(library(UserNetR))
library(coda)
library(tidyverse)
library(GGally)
#library(rebus)
library(tm)
library(tidyr)
library(tidytext)
'%out%' <- Negate ('%in%')
load("n_enron.Rda")
data(stop_words)

```

### Information sought

Prior to the investigation that resulted in the an initial staff report, FERC received a report from the California agency responsible for operating the electric energy exchange that FERC was concerned that the market had been manipulating.^[Frank A. Wolak, Chairman, Market Surveillance Committee of California Independent System Operator, *Report on Redesign of California Real-Time Energy and Ancillary Services Markets* dated October 18, 1999], which will be referred to as the [Wolak report].

The [Wolak report] was prepared before FERC began its investigation, did not rely on the Enron email corpus^[The report does not even name Enron.] and provides a lengthy analysis of the indicia of the exercise of market power in the California electricity wholesale market. A topical and keyword digest was prepared, as discussed below, to identify subjects of interest in the corpus.

# digest Wolak here

## Identification of high-value witnesses

# Results

### Resulting dataset

For purposes of this paper, the resulting tibble has been serialized to an `Rda` [file](https://s3-us-west–2.amazonaws.com/dslabs.nostromo/g_enron.Rda) of approximately [ ] size, which can be brought into an `R` session with the following 

      # syntax to load Rda from S3
      con <- url("https://s3-us-west-2.amazonaws.com/dslabs.nostromo/g_enron.Rda")
      load(con)
      close(con)

# Conclusion

# Credits

