options(java.parameters = "-Xmx8000m")
setwd("projects/enron")
library(coda)
library(cleanNLP)
library(tidyverse)
library(GGally)
library(tm)
library(tidyr)
library(tidytext)
'%out%' <- Negate ('%in%')
load("n_enron.Rda")
data(stop_words)
cnlp_init_corenlp("en", anno_level = 2, mem = "12g")
cnlp_init_tokenizers()
n1_text <- n_enron %>% filter(f_cluster == 1) %>% select(payload)
n2_text <- n_enron %>% filter(f_cluster == 2) %>% select(payload)
n3_text <- n_enron %>% filter(f_cluster == 3) %>% select(payload)

n1_obj <- cnlp_annotate(n1_text, as_strings = TRUE)
n2_obj <- cnlp_annotate(n1_text, as_strings = TRUE)
n3_obj <- cnlp_annotate(n3_text, as_strings = TRUE)
